CREATE TABLE IF NOT EXISTS cab_bookings (
  id INT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  source VARCHAR(100) NOT NULL,
  dest VARCHAR(100) NOT NULL,
  distance FLOAT NOT NULL,
  cab_type VARCHAR(20) NOT NULL,
  vehicle_no VARCHAR(20) NOT NULL,
  rate_per_km INT NOT NULL,
  total_fare FLOAT NOT NULL,
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cab_bookings_auto (
  id INT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  source VARCHAR(100) NOT NULL,
  dest VARCHAR(100) NOT NULL,
  distance FLOAT NOT NULL,
  cab_type VARCHAR(20) NOT NULL DEFAULT 'Auto',
  vehicle_no VARCHAR(20) NOT NULL,
  rate_per_km INT NOT NULL,
  total_fare FLOAT NOT NULL,
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cab_bookings_mini (
  id INT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  source VARCHAR(100) NOT NULL,
  dest VARCHAR(100) NOT NULL,
  distance FLOAT NOT NULL,
  cab_type VARCHAR(20) NOT NULL DEFAULT 'Mini',
  vehicle_no VARCHAR(20) NOT NULL,
  rate_per_km INT NOT NULL,
  total_fare FLOAT NOT NULL,
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cab_bookings_sedan (
  id INT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  source VARCHAR(100) NOT NULL,
  dest VARCHAR(100) NOT NULL,
  distance FLOAT NOT NULL,
  cab_type VARCHAR(20) NOT NULL DEFAULT 'Sedan',
  vehicle_no VARCHAR(20) NOT NULL,
  rate_per_km INT NOT NULL,
  total_fare FLOAT NOT NULL,
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cab_bookings_suv (
  id INT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  source VARCHAR(100) NOT NULL,
  dest VARCHAR(100) NOT NULL,
  distance FLOAT NOT NULL,
  cab_type VARCHAR(20) NOT NULL DEFAULT 'SUV',
  vehicle_no VARCHAR(20) NOT NULL,
  rate_per_km INT NOT NULL,
  total_fare FLOAT NOT NULL,
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;